"""add wakeup and routine tables

Revision ID: 5e5fbd2bc561
Revises: f6cbb2ea04eb
Create Date: 2026-05-03 12:30:58.663607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
import sqlmodel  # noqa: F401  -- SQLModel types referenced in generated columns

_JSON = sa.JSON().with_variant(JSONB(), "postgresql")


# revision identifiers, used by Alembic.
revision: str = '5e5fbd2bc561'
down_revision: Union[str, Sequence[str], None] = 'f6cbb2ea04eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule_kind', sa.Enum('EVERY_SECONDS', name='routineschedule'), nullable=False),
    sa.Column('schedule_value', sa.Integer(), nullable=False),
    sa.Column('payload', _JSON, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routine_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_routine_last_fired_at'), ['last_fired_at'], unique=False)

    op.create_table('wakeup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', _JSON, nullable=False),
    sa.Column('fire_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_FLIGHT', 'DONE', 'FAILED', 'CANCELLED', name='wakeupstatus'), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('routine_id', sa.Uuid(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wakeup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wakeup_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wakeup_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wakeup_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_wakeup_fire_at'), ['fire_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wakeup_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_wakeup_routine_id'), ['routine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wakeup_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wakeup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wakeup_status'))
        batch_op.drop_index(batch_op.f('ix_wakeup_routine_id'))
        batch_op.drop_index(batch_op.f('ix_wakeup_kind'))
        batch_op.drop_index(batch_op.f('ix_wakeup_fire_at'))
        batch_op.drop_index(batch_op.f('ix_wakeup_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_wakeup_created_at'))
        batch_op.drop_index(batch_op.f('ix_wakeup_business_id'))

    op.drop_table('wakeup')
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_last_fired_at'))
        batch_op.drop_index(batch_op.f('ix_routine_enabled'))
        batch_op.drop_index(batch_op.f('ix_routine_business_id'))

    op.drop_table('routine')
    # ### end Alembic commands ###
