"""add repo table

Revision ID: 6bd605409bea
Revises: 5e5fbd2bc561
Create Date: 2026-05-03 12:33:35.323328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  -- SQLModel types referenced in generated columns


# revision identifiers, used by Alembic.
revision: str = '6bd605409bea'
down_revision: Union[str, Sequence[str], None] = '5e5fbd2bc561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repo_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_name'))
        batch_op.drop_index(batch_op.f('ix_repo_business_id'))

    op.drop_table('repo')
    # ### end Alembic commands ###
