"""founder.active_business_id

Revision ID: 76d735c62c97
Revises: 6bd605409bea
Create Date: 2026-05-03 16:23:33.174832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  -- SQLModel types referenced in generated columns


# revision identifiers, used by Alembic.
revision: str = '76d735c62c97'
down_revision: Union[str, Sequence[str], None] = '6bd605409bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_business_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_founder_active_business',
            'business',
            ['active_business_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder', schema=None) as batch_op:
        batch_op.drop_constraint('fk_founder_active_business', type_='foreignkey')
        batch_op.drop_column('active_business_id')

    # ### end Alembic commands ###
