"""task.ref_number

Revision ID: e3ef525a92e1
Revises: 76d735c62c97
Create Date: 2026-05-03 17:49:08.670144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  -- SQLModel types referenced in generated columns


# revision identifiers, used by Alembic.
revision: str = 'e3ef525a92e1'
down_revision: Union[str, Sequence[str], None] = '76d735c62c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_number', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_ref_number'), ['ref_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_ref_number'))
        batch_op.drop_column('ref_number')

    # ### end Alembic commands ###
