"""add message_summary table

Revision ID: f6cbb2ea04eb
Revises: fbc95410cbce
Create Date: 2026-05-03 12:26:14.060352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  -- SQLModel types referenced in generated columns


# revision identifiers, used by Alembic.
revision: str = 'f6cbb2ea04eb'
down_revision: Union[str, Sequence[str], None] = 'fbc95410cbce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_summary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('summary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('covers_until', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_summary_covers_until'), ['covers_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_summary_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_summary_thread_id'))
        batch_op.drop_index(batch_op.f('ix_message_summary_covers_until'))

    op.drop_table('message_summary')
    # ### end Alembic commands ###
