"""initial schema

Revision ID: fbc95410cbce
Revises: 
Create Date: 2026-05-03 11:52:22.165612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
import sqlmodel  # noqa: F401

# JSONB on Postgres, JSON on SQLite — same pattern as korpha.db._base.json_column.
_JSON = sa.JSON().with_variant(JSONB(), "postgresql")


# revision identifiers, used by Alembic.
revision: str = 'fbc95410cbce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('founder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferences', _JSON, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('founder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_founder_email'), ['email'], unique=True)

    op.create_table('business',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('founder_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('IDEA', 'VALIDATING', 'LAUNCHED', 'RUNNING', 'PAUSED', 'SHUT_DOWN', name='businessstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['founder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_founder_id'), ['founder_id'], unique=False)

    op.create_table('activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('FOUNDER', 'AGENT', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', _JSON, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_event_type'), ['event_type'], unique=False)

    op.create_table('agent_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('role_type', sa.Enum('CEO', 'CTO', 'CMO', 'COO', 'CHIEF_OF_STAFF', 'WORKER', name='roletype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hired_at', sa.DateTime(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.Column('personality_config', _JSON, nullable=False),
    sa.Column('inference_tier_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_role_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_role_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_role_role_type'), ['role_type'], unique=False)

    op.create_table('goal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('parent_goal_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_metric', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACHIEVED', 'ABANDONED', name='goalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_business_id'), ['business_id'], unique=False)

    op.create_table('trust_envelope',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('action_class', sa.Enum('INTERNAL', 'HIRE_AGENT', 'CODE_CHANGE', 'PUBLIC_POST', 'EMAIL_OUTREACH', 'EMAIL_REPLY', 'SPEND', 'SUPPORT_REPLY', name='actionclass'), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consecutive_approvals', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('DRAFT', 'AUTO', 'OFF', name='autonomymode'), nullable=False),
    sa.Column('last_decision_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_envelope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_envelope_action_class'), ['action_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_envelope_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_envelope_platform'), ['platform'], unique=False)

    op.create_table('approval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('agent_role_id', sa.Uuid(), nullable=False),
    sa.Column('action_class', sa.Enum('INTERNAL', 'HIRE_AGENT', 'CODE_CHANGE', 'PUBLIC_POST', 'EMAIL_OUTREACH', 'EMAIL_REPLY', 'SPEND', 'SUPPORT_REPLY', name='actionclass'), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proposal_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_payload', _JSON, nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MODIFIED', 'AUTO_EXECUTED', 'EXPIRED', name='approvalstatus'), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modification_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_role_id'], ['agent_role.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_action_class'), ['action_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_agent_role_id'), ['agent_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_status'), ['status'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'DONE', 'BLOCKED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_business_id'), ['business_id'], unique=False)

    op.create_table('thread',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('founder_id', sa.Uuid(), nullable=False),
    sa.Column('agent_role_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('WEB', 'TELEGRAM', 'DISCORD', 'EMAIL', 'SLACK', 'WHATSAPP', 'SIGNAL', name='threadplatform'), nullable=False),
    sa.Column('platform_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sticky_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='threadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_role_id'], ['agent_role.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['founder_id'], ['founder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_agent_role_id'), ['agent_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_founder_id'), ['founder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_platform_thread_id'), ['platform_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_status'), ['status'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.Enum('FOUNDER', 'AGENT', 'SYSTEM', name='messagesendertype'), nullable=False),
    sa.Column('sender_role_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachments', _JSON, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_role_id'], ['agent_role.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_thread_id'), ['thread_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_role_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_role_id'], ['agent_role.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assigned_to_role_id'), ['assigned_to_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_business_id'), ['business_id'], unique=False)

    op.create_table('blocker',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('requesting_agent_role_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('DECISION', 'INFO', 'APPROVAL', 'PERMISSION', 'RESOURCE', 'CLARIFICATION', 'OTHER', name='blockerkind'), nullable=False),
    sa.Column('urgency', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='blockerurgency'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'RESOLVED_BY_COS', 'AWAITING_FOUNDER', 'RESOLVED', 'DROPPED', name='blockerstatus'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', _JSON, nullable=False),
    sa.Column('cos_recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cos_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deduped_into_id', sa.Uuid(), nullable=True),
    sa.Column('parent_blocker_id', sa.Uuid(), nullable=True),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolution_meta', _JSON, nullable=False),
    sa.Column('resolved_by_founder_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('triaged_at', sa.DateTime(), nullable=True),
    sa.Column('surfaced_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approval.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['deduped_into_id'], ['blocker.id'], ),
    sa.ForeignKeyConstraint(['parent_blocker_id'], ['blocker.id'], ),
    sa.ForeignKeyConstraint(['requesting_agent_role_id'], ['agent_role.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_founder_id'], ['founder.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocker_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_requesting_agent_role_id'), ['requesting_agent_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_topic_tag'), ['topic_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_urgency'), ['urgency'], unique=False)

    op.create_table('cost',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('agent_role_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sa.Enum('WORKHORSE', 'PRO', 'CONSULTANT', name='inferencetier'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_role_id'], ['agent_role.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_tier'), ['tier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_tier'))
        batch_op.drop_index(batch_op.f('ix_cost_provider'))
        batch_op.drop_index(batch_op.f('ix_cost_model'))
        batch_op.drop_index(batch_op.f('ix_cost_created_at'))
        batch_op.drop_index(batch_op.f('ix_cost_business_id'))

    op.drop_table('cost')
    with op.batch_alter_table('blocker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocker_urgency'))
        batch_op.drop_index(batch_op.f('ix_blocker_topic_tag'))
        batch_op.drop_index(batch_op.f('ix_blocker_title'))
        batch_op.drop_index(batch_op.f('ix_blocker_task_id'))
        batch_op.drop_index(batch_op.f('ix_blocker_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_blocker_status'))
        batch_op.drop_index(batch_op.f('ix_blocker_requesting_agent_role_id'))
        batch_op.drop_index(batch_op.f('ix_blocker_kind'))
        batch_op.drop_index(batch_op.f('ix_blocker_business_id'))

    op.drop_table('blocker')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_business_id'))
        batch_op.drop_index(batch_op.f('ix_task_assigned_to_role_id'))

    op.drop_table('task')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_thread_id'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    op.drop_table('message')
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_status'))
        batch_op.drop_index(batch_op.f('ix_thread_platform_thread_id'))
        batch_op.drop_index(batch_op.f('ix_thread_platform'))
        batch_op.drop_index(batch_op.f('ix_thread_founder_id'))
        batch_op.drop_index(batch_op.f('ix_thread_business_id'))
        batch_op.drop_index(batch_op.f('ix_thread_agent_role_id'))

    op.drop_table('thread')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_business_id'))

    op.drop_table('project')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_status'))
        batch_op.drop_index(batch_op.f('ix_approval_platform'))
        batch_op.drop_index(batch_op.f('ix_approval_created_at'))
        batch_op.drop_index(batch_op.f('ix_approval_business_id'))
        batch_op.drop_index(batch_op.f('ix_approval_agent_role_id'))
        batch_op.drop_index(batch_op.f('ix_approval_action_class'))

    op.drop_table('approval')
    with op.batch_alter_table('trust_envelope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_envelope_platform'))
        batch_op.drop_index(batch_op.f('ix_trust_envelope_business_id'))
        batch_op.drop_index(batch_op.f('ix_trust_envelope_action_class'))

    op.drop_table('trust_envelope')
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_business_id'))

    op.drop_table('goal')
    with op.batch_alter_table('agent_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_role_role_type'))
        batch_op.drop_index(batch_op.f('ix_agent_role_is_active'))
        batch_op.drop_index(batch_op.f('ix_agent_role_business_id'))

    op.drop_table('agent_role')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_event_type'))
        batch_op.drop_index(batch_op.f('ix_activity_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_business_id'))
        batch_op.drop_index(batch_op.f('ix_activity_actor_type'))
        batch_op.drop_index(batch_op.f('ix_activity_actor_id'))

    op.drop_table('activity')
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_founder_id'))

    op.drop_table('business')
    with op.batch_alter_table('founder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_founder_email'))

    op.drop_table('founder')
    # ### end Alembic commands ###
