"""Write/append entries to ``providers.yaml``.

Used by the ``korpha config`` wizard so non-technical Founders never
have to hand-edit YAML. Keeps the existing entries intact when
appending — round-trip preserves comments only when the file was
originally written by us (PyYAML loses comments on round-trip; that's
acceptable since this file is generated by the wizard, not human-edited).
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from korpha.inference.config import config_path


def append_provider_entry(
    entry: dict[str, Any],
    *,
    path: Path | None = None,
) -> Path:
    """Append a provider entry to ``providers.yaml``, creating the file
    + parent dirs if missing. Returns the resolved path."""
    import yaml

    p = path or config_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    if p.exists():
        existing = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        if not isinstance(existing, dict):
            raise ValueError(
                f"{p}: top level must be a mapping, got {type(existing).__name__}"
            )
        providers = existing.get("providers")
        if providers is None:
            existing["providers"] = [entry]
        elif isinstance(providers, list):
            providers.append(entry)
        else:
            raise ValueError(f"{p}: 'providers' must be a list")
        body = existing
    else:
        body = {"providers": [entry]}

    yaml_text = yaml.safe_dump(body, sort_keys=False, default_flow_style=False)
    p.write_text(yaml_text, encoding="utf-8")
    # Tighten permissions — file may contain inline api_key.
    # Best-effort; Windows / odd filesystems may not support it.
    import contextlib

    with contextlib.suppress(OSError):
        os.chmod(p, 0o600)
    return p


def remove_provider_entry(label: str, *, path: Path | None = None) -> bool:
    """Remove the first entry whose ``label`` matches. Returns True if a
    row was removed, False if no match (or file missing). Caller decides
    how to surface the False case."""
    import yaml

    p = path or config_path()
    if not p.exists():
        return False
    body = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    if not isinstance(body, dict):
        return False
    providers = body.get("providers")
    if not isinstance(providers, list):
        return False
    for i, entry in enumerate(providers):
        if isinstance(entry, dict) and str(entry.get("label") or "") == label:
            providers.pop(i)
            yaml_text = yaml.safe_dump(body, sort_keys=False, default_flow_style=False)
            p.write_text(yaml_text, encoding="utf-8")
            return True
    return False


def update_provider_entry(
    label: str,
    fields: dict[str, Any],
    *,
    path: Path | None = None,
) -> bool:
    """Merge ``fields`` into the first entry whose ``label`` matches.
    Returns True if a row was updated, False if the file is missing or
    no row matched. Pass ``{"key": None}`` to remove a key.

    Used by the ``korpha inference set-*`` CLI commands so Mike can
    tune cascade priority / retries / free-tier quotas without editing
    YAML."""
    import yaml

    p = path or config_path()
    if not p.exists():
        return False
    body = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    if not isinstance(body, dict):
        return False
    providers = body.get("providers")
    if not isinstance(providers, list):
        return False
    for entry in providers:
        if isinstance(entry, dict) and str(entry.get("label") or "") == label:
            for k, v in fields.items():
                if v is None:
                    entry.pop(k, None)
                else:
                    entry[k] = v
            yaml_text = yaml.safe_dump(body, sort_keys=False, default_flow_style=False)
            p.write_text(yaml_text, encoding="utf-8")
            import contextlib
            with contextlib.suppress(OSError):
                os.chmod(p, 0o600)
            return True
    return False


__all__ = [
    "append_provider_entry",
    "remove_provider_entry",
    "update_provider_entry",
]
